name: "Build and Deploy"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  builddeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
      - name: Install Dependencies
        run: npm install
      - name: Create .env.local
        run: |
          echo "NEXT_PUBLIC_API_HOST=${{secrets.API_HOST}}" > .env.local
          echo "NEXT_PUBLIC_API_PROTOCOL=${{secrets.API_PROTOCOL}}" >> .env.local
          echo "NEXT_PUBLIC_API_HOSTNAME=${{secrets.API_HOSTNAME}}" >> .env.local
          echo "NEXT_PUBLIC_API_PORT=${{secrets.API_PORT}}" >> .env.local
          echo "NEXT_PUBLIC_API_MEDIA_PATHNAME=${{secrets.MEDIA_PATH}}" >> .env.local
      - name: Build App
        run: npm run build