name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin
            npm run build
            pm2 restart ${{ secrets.PM2_NAME }}
            